;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagRedirects=(OldTagName="Ability.Attack.Physical.Network",NewTagName="Ability.Attack.Physical.Ranged")
GameplayTagList=(Tag="Ability.Network",DevComment="")
GameplayTagList=(Tag="Ability.Network.Attack",DevComment="")
GameplayTagList=(Tag="Ability.Network.Attack.Melee",DevComment="")
GameplayTagList=(Tag="Ability.Network.Attack.Ranged",DevComment="")
GameplayTagList=(Tag="Ability.Network.Buff",DevComment="")
GameplayTagList=(Tag="Ability.Network.Buff.TissueRelay",DevComment="")
GameplayTagList=(Tag="Ability.Network.Debuff",DevComment="")
GameplayTagList=(Tag="Ability.Network.Debuff.DisruptiveShock",DevComment="")
GameplayTagList=(Tag="Ability.Network.Debuff.FirewallBurnout",DevComment="")
GameplayTagList=(Tag="Ability.Network.Debuff.FragmentationLeak",DevComment="")
GameplayTagList=(Tag="Ability.Network.Debuff.MagneticDestabilizer",DevComment="")
GameplayTagList=(Tag="Ability.Network.Debuff.OverclockMeltdown",DevComment="")
GameplayTagList=(Tag="Ability.Network.Debuff.RadiationPulse",DevComment="")
GameplayTagList=(Tag="Ability.Physical",DevComment="")
GameplayTagList=(Tag="Ability.Physical.Attack",DevComment="")
GameplayTagList=(Tag="Ability.Physical.Attack.Melee",DevComment="")
GameplayTagList=(Tag="Ability.Physical.Attack.Melee.Heavy",DevComment="")
GameplayTagList=(Tag="Ability.Physical.Attack.Melee.Light",DevComment="")
GameplayTagList=(Tag="Ability.Physical.Attack.Melee.Offhand",DevComment="")
GameplayTagList=(Tag="Ability.Physical.Attack.Melee.Unarmed",DevComment="")
GameplayTagList=(Tag="Ability.Physical.Attack.Ranged",DevComment="")
GameplayTagList=(Tag="Ability.Physical.Attack.Ranged.Heavy",DevComment="")
GameplayTagList=(Tag="Ability.Physical.Attack.Ranged.Light",DevComment="")
GameplayTagList=(Tag="Ability.Physical.Attack.Ranged.Offhand",DevComment="")
GameplayTagList=(Tag="Ability.Physical.Buff",DevComment="")
GameplayTagList=(Tag="Ability.Physical.Debuff",DevComment="")

