[/Script/EngineSettings.GameMapsSettings]
GameDefaultMap=/Game/TopDown/Lvl_TopDown.Lvl_TopDown
EditorStartupMap=/Game/UmutTestLevel.UmutTestLevel
GlobalDefaultGameMode=/Game/TopDown/Blueprints/BP_TopDownGameMode.BP_TopDownGameMode_C

[/Script/Engine.RendererSettings]
r.DefaultFeature.AutoExposure.ExtendDefaultLuminanceRange=True
r.DefaultFeature.AutoExposure.ExtendDefaultLuminanceRange=true
r.AllowStaticLighting=False

r.GenerateMeshDistanceFields=True

r.DynamicGlobalIlluminationMethod=1

r.ReflectionMethod=1

r.SkinCache.CompileShaders=True

r.RayTracing.RayTracingProxies.ProjectEnabled=True

r.Shadow.Virtual.Enable=1

r.DefaultFeature.LocalExposure.HighlightContrastScale=0.8

r.DefaultFeature.LocalExposure.ShadowContrastScale=0.8
r.GPUSkin.Support16BitBoneIndex=True
r.GPUSkin.UnlimitedBoneInfluences=True
SkeletalMesh.UseExperimentalChunking=1
r.CustomDepth=3

[/Script/WindowsTargetPlatform.WindowsTargetSettings]
DefaultGraphicsRHI=DefaultGraphicsRHI_DX12
DefaultGraphicsRHI=DefaultGraphicsRHI_DX12
-D3D12TargetedShaderFormats=PCD3D_SM5
+D3D12TargetedShaderFormats=PCD3D_SM6
-D3D11TargetedShaderFormats=PCD3D_SM5
+D3D11TargetedShaderFormats=PCD3D_SM5
Compiler=Default
AudioSampleRate=48000
AudioCallbackBufferFrameSize=1024
AudioNumBuffersToEnqueue=1
AudioMaxChannels=0
AudioNumSourceWorkers=4
SpatializationPlugin=
SourceDataOverridePlugin=
ReverbPlugin=
OcclusionPlugin=
CompressionOverrides=(bOverrideCompressionTimes=False,DurationThreshold=5.000000,MaxNumRandomBranches=0,SoundCueQualityIndex=0)
CacheSizeKB=65536
MaxChunkSizeOverrideKB=0
bResampleForDevice=False
MaxSampleRate=48000.000000
HighSampleRate=32000.000000
MedSampleRate=24000.000000
LowSampleRate=12000.000000
MinSampleRate=8000.000000
CompressionQualityModifier=1.000000
AutoStreamingThreshold=0.000000
SoundCueCookQualityIndex=-1

[/Script/LinuxTargetPlatform.LinuxTargetSettings]
-TargetedRHIs=SF_VULKAN_SM5
+TargetedRHIs=SF_VULKAN_SM6

[CoreRedirects]
+ClassRedirects=(OldName="/Script/TopDownCPP.StrategyGameMode",NewName="/Script/RizzGame.StrategyGameMode")
+ClassRedirects=(OldName="/Script/TopDownCPP.StrategyHUD",NewName="/Script/RizzGame.StrategyHUD")
+ClassRedirects=(OldName="/Script/TopDownCPP.StrategyPawn",NewName="/Script/RizzGame.StrategyPawn")
+ClassRedirects=(OldName="/Script/TopDownCPP.StrategyPlayerController",NewName="/Script/RizzGame.StrategyPlayerController")
+ClassRedirects=(OldName="/Script/TopDownCPP.StrategyUI",NewName="/Script/RizzGame.StrategyUI")
+ClassRedirects=(OldName="/Script/TopDownCPP.StrategyNPC",NewName="/Script/RizzGame.StrategyUnit")

+ClassRedirects=(OldName="/Script/TopDownCPP.TwinStickAIController",NewName="/Script/RizzGame.TwinStickAIController")
+ClassRedirects=(OldName="/Script/TopDownCPP.TwinStickNPC",NewName="/Script/RizzGame.TwinStickNPC")
+ClassRedirects=(OldName="/Script/TopDownCPP.TwinStickAoEAttack",NewName="/Script/RizzGame.TwinStickAoEAttack")
+ClassRedirects=(OldName="/Script/TopDownCPP.TwinStickCharacter",NewName="/Script/RizzGame.TwinStickCharacter")
+ClassRedirects=(OldName="/Script/TopDownCPP.TwinStickGameMode",NewName="/Script/RizzGame.TwinStickGameMode")
+ClassRedirects=(OldName="/Script/TopDownCPP.TwinStickNPCDestruction",NewName="/Script/RizzGame.TwinStickNPCDestruction")
+ClassRedirects=(OldName="/Script/TopDownCPP.TwinStickPickup",NewName="/Script/RizzGame.TwinStickPickup")
+ClassRedirects=(OldName="/Script/TopDownCPP.TwinStickPlayerController",NewName="/Script/RizzGame.TwinStickPlayerController")
+ClassRedirects=(OldName="/Script/TopDownCPP.TwinStickProjectile",NewName="/Script/RizzGame.TwinStickProjectile")
+ClassRedirects=(OldName="/Script/TopDownCPP.TwinStickSpawner",NewName="/Script/RizzGame.TwinStickSpawner")
+ClassRedirects=(OldName="/Script/TopDownCPP.TwinStickUI",NewName="/Script/RizzGame.TwinStickUI")
+PropertyRedirects=(OldName="/Script/RizzGame.RizzGameGameMode.PlayerChracter",NewName="/Script/RizzGame.RizzGameGameMode.PlayerCharacter")
+PropertyRedirects=(OldName="/Script/RizzGame.RPlayerControllerBase.DefaultMappingContext",NewName="/Script/RizzGame.RPlayerControllerBase.CameraMappingContext")
+PropertyRedirects=(OldName="/Script/RizzGame.RPlayerControllerBase.MoveAction",NewName="/Script/RizzGame.RPlayerControllerBase.CameraMoveAction")
+PropertyRedirects=(OldName="/Script/RizzGame.RPawn.Controller",NewName="/Script/RizzGame.RPawn.SelectedCharacter")
+PropertyRedirects=(OldName="/Script/RizzGame.RPawn.RController",NewName="/Script/RizzGame.RPawn.SelectedCharacter")
+ClassRedirects=(OldName="/Script/RizzGame.RAttributeSet",NewName="/Script/RizzGame.RChracterAttributeSet")
+PropertyRedirects=(OldName="/Script/RizzGame.RTurnManagerSubsystem.combatants",NewName="/Script/RizzGame.RCombatManagerSubsystem.Combatants")
+PropertyRedirects=(OldName="/Script/RizzGame.ChangeStateData.TurnComponent",NewName="/Script/RizzGame.ChangeStateData.Actor")
+PropertyRedirects=(OldName="/Script/RizzGame.ChangeStateData.efect",NewName="/Script/RizzGame.ChangeStateData.Efect")
+FunctionRedirects=(OldName="/Script/RizzGame.RGameplayAbilityBase.GetLocationUnderCursor",NewName="/Script/RizzGame.RGameplayAbilityBase.GetHitResultUnderCursor")
+PropertyRedirects=(OldName="/Script/RizzGame.RGameplayAbilityBase.Distance",NewName="/Script/RizzGame.RGameplayAbilityBase.Range")
+PropertyRedirects=(OldName="/Script/RizzGame.RDefaultButton.Icon",NewName="/Script/RizzGame.RDefaultButton.IMG_Icon")
+PropertyRedirects=(OldName="/Script/RizzGame.RDefaultButton.Background",NewName="/Script/RizzGame.RDefaultButton.B_Background")
+PropertyRedirects=(OldName="/Script/RizzGame.RDefaultButton.Hover_In",NewName="/Script/RizzGame.RDefaultButton.WA_HoverIn")
+PropertyRedirects=(OldName="/Script/RizzGame.RDefaultButton.Hover_Out",NewName="/Script/RizzGame.RDefaultButton.WA_HoverOut")
+PropertyRedirects=(OldName="/Script/RizzGame.RDefaultButton.Press",NewName="/Script/RizzGame.RDefaultButton.WA_Press")
+PropertyRedirects=(OldName="/Script/RizzGame.RDefaultButton.Disable_Enable",NewName="/Script/RizzGame.RDefaultButton.WA_DisableEnable")
+PropertyRedirects=(OldName="/Script/RizzGame.RDefaultButton.HoverBackground",NewName="/Script/RizzGame.RDefaultButton.B_HoverBackground")
+PropertyRedirects=(OldName="/Script/RizzGame.RDefaultButton.PressedBackground",NewName="/Script/RizzGame.RDefaultButton.B_PressedBackground")
+PropertyRedirects=(OldName="/Script/RizzGame.RDefaultButton.DisabledBackground",NewName="/Script/RizzGame.RDefaultButton.B_DisabledBackground")
+PropertyRedirects=(OldName="/Script/RizzGame.RDefaultButton.DisabledIcon",NewName="/Script/RizzGame.RDefaultButton.IMG_DisabledIcon") 
+ClassRedirects=(OldName="/Script/RizzGame.RTurnManagerSubsystem",NewName="/Script/RizzGame.RCombatManagerSubsystem")
+ClassRedirects=(OldName="/Script/RizzGame.RCombatInitiativeQueue",NewName="/Script/RizzGame.RCombatInitiativeQueueWidget")
+PropertyRedirects=(OldName="/Script/RizzGame.CombatInitiativeChanged.NewOrder",NewName="/Script/RizzGame.CombatInitiativeChanged.Combatants")
+FunctionRedirects=(OldName="/Script/RizzGame.RInventoryComponent.GetEntries",NewName="/Script/RizzGame.RInventoryComponent.GetItemsWithoutReference")
+PropertyRedirects=(OldName="/Script/RizzGame.RGA_Attack.AnimMontage",NewName="/Script/RizzGame.RGA_Attack.AbilityExecuteMontage")
+ClassRedirects=(OldName="/Script/RizzGame.MyClass",NewName="/Script/RizzGame.BTTask_EndTurn")
+ClassRedirects=(OldName="/Script/RizzGame.UBTDecorator_CheckTargetHealth",NewName="/Script/RizzGame.BTDecorator_CheckTargetHealth")
+ClassRedirects=(OldName="/Script/RizzGame.BTDecorator_HasAP",NewName="/Script/RizzGame.BTDecorator_WalkDistanceFinished")
+ClassRedirects=(OldName="/Script/RizzGame.BTDecorator_HasWalkDistance",NewName="/Script/RizzGame.BTDecorator_WalkDistanceFinished")

;+StructRedirects=(OldName="MyStruct",NewName="MyNewStruct")
;+StructRedirects=(OldName="MyStruct",NewName="MyNewStruct")

[/Script/NavigationSystem.RecastNavMesh]
RuntimeGeneration=Dynamic


[/Script/HardwareTargeting.HardwareTargetingSettings]
TargetedHardwareClass=Desktop
AppliedTargetedHardwareClass=Desktop
DefaultGraphicsPerformance=Maximum
AppliedDefaultGraphicsPerformance=Maximum

[/Script/Engine.Engine]
+ActiveGameNameRedirects=(OldGameName="TP_TopDown",NewGameName="/Script/RizzGame")
+ActiveGameNameRedirects=(OldGameName="/Script/TP_TopDown",NewGameName="/Script/RizzGame")
+ActiveClassRedirects=(OldClassName="TP_TopDownPlayerController",NewClassName="RizzGamePlayerController")
+ActiveClassRedirects=(OldClassName="TP_TopDownGameMode",NewClassName="RizzGameGameMode")
+ActiveClassRedirects=(OldClassName="TP_TopDownCharacter",NewClassName="RizzGameCharacter")
SmoothedFrameRateRange=(LowerBound=(Type=Inclusive,Value=22.000000),UpperBound=(Type=Exclusive,Value=144.000000))
bUseFixedFrameRate=False
FixedFrameRate=500.000000

[/Script/AndroidFileServerEditor.AndroidFileServerRuntimeSettings]
bEnablePlugin=True
bAllowNetworkConnection=True
SecurityToken=8A3820F9482F2A596ACEAE8553607E87
bIncludeInShipping=False
bAllowExternalStartInShipping=False
bCompileAFSProject=False
bUseCompression=False
bLogFiles=False
bReportStats=False
ConnectionType=USBOnly
bUseManualIPAddress=False
ManualIPAddress=

[/Script/GameplayDebugger.GameplayDebuggerConfig]
ActivationKey=Semicolon
CategoryRowNextKey=Add
CategoryRowPrevKey=Subtract
CategorySlot0=NumPadZero
CategorySlot1=NumPadOne
CategorySlot2=NumPadTwo
CategorySlot3=NumPadThree
CategorySlot4=Four
CategorySlot5=Five
CategorySlot6=Six
CategorySlot7=NumPadSeven
CategorySlot8=NumPadEight
CategorySlot9=NumPadNine
DebugCanvasPaddingLeft=10.000000
DebugCanvasPaddingRight=10.000000
DebugCanvasPaddingTop=10.000000
DebugCanvasPaddingBottom=10.000000
bDebugCanvasEnableTextShadow=False
+Categories=(CategoryName="Abilities",SlotIdx=-1,ActiveInGame=UseDefault,ActiveInSimulate=UseDefault,Hidden=UseDefault,bOverrideSlotIdx=False,InputHandlers=)
+Categories=(CategoryName="AI",SlotIdx=1,ActiveInGame=UseDefault,ActiveInSimulate=UseDefault,Hidden=UseDefault,bOverrideSlotIdx=False,InputHandlers=)
+Categories=(CategoryName="BehaviorTree",SlotIdx=2,ActiveInGame=UseDefault,ActiveInSimulate=UseDefault,Hidden=UseDefault,bOverrideSlotIdx=False,InputHandlers=)
+Categories=(CategoryName="EQS",SlotIdx=-1,ActiveInGame=UseDefault,ActiveInSimulate=UseDefault,Hidden=UseDefault,bOverrideSlotIdx=False,InputHandlers=((ConfigName="CycleQueries",Key=Multiply),(ConfigName="ToggleDetails",Key=Divide)))
+Categories=(CategoryName="Navmesh",SlotIdx=0,ActiveInGame=UseDefault,ActiveInSimulate=UseDefault,Hidden=UseDefault,bOverrideSlotIdx=False,InputHandlers=((ConfigName="Cycle Actor Reference",Key=Subtract,bModShift=True),(ConfigName="Cycle NavData",Key=Add,bModShift=True),(ConfigName="Lock Reference Location",Key=Multiply,bModShift=True)))
+Categories=(CategoryName="Perception",SlotIdx=-1,ActiveInGame=UseDefault,ActiveInSimulate=UseDefault,Hidden=UseDefault,bOverrideSlotIdx=False,InputHandlers=)
+Categories=(CategoryName="PerceptionSystem",SlotIdx=-1,ActiveInGame=UseDefault,ActiveInSimulate=UseDefault,Hidden=UseDefault,bOverrideSlotIdx=False,InputHandlers=)
+Categories=(CategoryName="NavGrid",SlotIdx=-1,ActiveInGame=UseDefault,ActiveInSimulate=UseDefault,Hidden=UseDefault,bOverrideSlotIdx=False,InputHandlers=)
+Extensions=(ExtensionName="GameHUD",UseExtension=UseDefault,InputHandlers=((ConfigName="ToggleHUD",Key=Quote,bModCtrl=True),(ConfigName="ToggleMessages",Key=Tab,bModCtrl=True)))
+Extensions=(ExtensionName="Spectator",UseExtension=UseDefault,InputHandlers=((ConfigName="Toggle",Key=Tab)))

[/Script/AIModule.AISystem]
bForgetStaleActors=True

